### ISSUE TITLE
win10运行出现x_ops.cpython-36m-darwin.so not found 

### ISSUE THREAD

**Issue by Longtimedly** [Delta-ML/delta#239]
C:\AI\delta-master\venv\Scripts\python.exe C:/AI/delta-master/delta/main.py
2020-09-25 13:31:57.339421: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
WARNING:tensorflow:From C:\AI\delta-master\venv\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:88: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
I0925 13:31:58.983651 17140 main.py:73] Loading all modules ...
I0925 13:31:58.991628 17140 py_x_ops.py:40] x_ops.so path:C:\AI\delta-master\core\ops\x_ops.cpython-36m-darwin.so
Traceback (most recent call last):
  File "C:/AI/delta-master/delta/main.py", line 138, in <module>
    entry()
  File "C:/AI/delta-master/delta/main.py", line 125, in entry
    app.run(main)
  File "C:\AI\delta-master\venv\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\AI\delta-master\venv\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "C:/AI/delta-master/delta/main.py", line 74, in main
    import_all_modules_for_register(config, only_nlp=FLAGS.only_nlp)
  File "C:\AI\delta-master\delta\utils\register.py", line 230, in import_all_modules_for_register
    importlib.import_module(full_name)
  File "C:\Program Files\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\AI\delta-master\delta\data\task\text_cls_task.py", line 22, in <module>
    from delta.data.task.base_text_task import TextTask
  File "C:\AI\delta-master\delta\data\task\base_text_task.py", line 24, in <module>
    from delta.data.preprocess.text_ops import clean_english_str_tf
  File "C:\AI\delta-master\delta\data\preprocess\text_ops.py", line 22, in <module>
    from core.ops import py_x_ops
  File "C:\AI\delta-master\core\ops\py_x_ops.py", line 41, in <module>
    gen_x_ops = tf.load_op_library(path)
  File "C:\AI\delta-master\venv\lib\site-packages\tensorflow_core\python\framework\load_library.py", line 57, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: C:\AI\delta-master\core\ops\x_ops.cpython-36m-darwin.so not found

更换了tensorflow-gpu2.0.0-2.2.0都有这个问题，tensorflow-addons==0.6.0没有提供windows版本，问下这个是环境造成的原因windows就是无法使用吗？x_ops.cpython-36m-darwin.so的路径是正确的，有这个文件存在的就是not found，这是什么原呢？
还有问下官方有没有QQ群之类的交流群吗？

**Comment by hankun11** [comment]
This problems is caused by unsupported operating systems... Sorry, unfortunately, we currently do not support Windows. Please use Linux or MacOS instead.
