### ISSUE TITLE
When I run IEMOCAP ,I got an error 

### ISSUE THREAD

**Issue by Luyizhe** [Delta-ML/delta#242]
When I bash run.sh,I got an error like below.

[ 2020-11-04 22:00:26,305 INFO          api.py:541   41096 ]  xxxx input: [], training: None
Traceback (most recent call last):
  File "/opt1/luyz/DiDiDelta/delta/./delta/main.py", line 145, in <module>
    entry()
  File "/opt1/luyz/DiDiDelta/delta/./delta/main.py", line 132, in entry
    app.run(main)
  File "/home/luyz/.conda/envs/py36/lib/python3.6/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/luyz/.conda/envs/py36/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/opt1/luyz/DiDiDelta/delta/./delta/main.py", line 93, in main
    solver.train_and_eval()
  File "/opt1/luyz/DiDiDelta/delta/delta/utils/solver/asr_solver.py", line 190, in train_and_eval
    self.model_fn(mode=utils.TRAIN)
  File "/opt1/luyz/DiDiDelta/delta/delta/utils/solver/keras_base_solver.py", line 140, in model_fn
    self.build(multi_gpu=(mode == utils.TRAIN))
  File "/opt1/luyz/DiDiDelta/delta/delta/utils/solver/keras_base_solver.py", line 154, in build
    self.model, gpus=self.ngpu, cpu_relocation=False, cpu_merge=False)
  File "/home/luyz/.local/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/luyz/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/multi_gpu_utils.py", line 240, in multi_gpu_model
    outputs = model(inputs)
  File "/home/luyz/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 847, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/luyz/.local/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in converted code:

    /opt1/luyz/DiDiDelta/delta/delta/models/speech_cls_model.py:149 call  *
        x = inputs['inputs']

    TypeError: list indices must be integers or slices, not str

Then I debug to identify the location of the error , I find that the variable 'ds_' doesn't get any value after the code 'ds_ = input_fn()' in 'asr_solver.py'.

I think I have correct dataset dir ,or I can't run the code to stage 5 .Please give me some help.

**Comment by Luyizhe** [comment]
I got the problem above when I used configuration file “emo-keras-blstm.yml”。Today，I found if I use "emotion-speech-cls.yml" , I can complete training steps.
